namespace StepManiaLibrary;

/// <summary>
/// Enumeration of methods for overwriting charts.
/// </summary>
public enum OverwriteBehavior
{
	/// <summary>
	/// Do no overwrite charts that match the output type.
	/// </summary>
	DoNotOverwrite,

	/// <summary>
	/// Overwrite existing charts if they were generated by this program.
	/// </summary>
	IfFumenGenerated,

	/// <summary>
	/// Overwrite existing charts if they were generated by this program and they
	/// were generated at an older version.
	/// </summary>
	IfFumenGeneratedAndNewerVersion,

	/// <summary>
	/// Always overwrite any existing charts.
	/// </summary>
	Always,
}
